apiVersion: v1
kind: Pod
metadata:
  name: postgres
spec:
  containers:
    - name: postgres
      image: postgres
      env:  # was missing
        - name: POSTGRES_PASSWORD  
          value: "supersecret"